---

PLUGINS:
  - https://raw.githubusercontent.com/kpj/jupyfmt/master/mega-linter-plugin-jupyfmt/jupyfmt.megalinter-descriptor.yml

ENABLE_LINTERS:
  - PYTHON_BLACK
  - R_LINTR
  - BASH_SHELLCHECK
  - SNAKEMAKE_SNAKEFMT
  - MARKDOWN_MARKDOWNLINT
  - JUPYTER_JUPYFMT

FORMATTERS_DISABLE_ERRORS: false

PRINT_ALPACA: false
